trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

name: $(BuildID)-$(Build.SourceBranchName)

resources:
- repo: self

variables:
  ${{ if notIn(variables['Build.SourceBranchName'], 'master', 'develop') }}:
    buildImage: false
    deployService: false
    deployEnvironment: 'no'
    imageTags: 'no'
    serviceName: 'no'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    buildImage: true
    deployService: true
    deployEnvironment: development
    imageTags: |
      $(Build.BuildId)
      develop
    serviceName: itlab_identity-develop
    serviceNameAdmin: itlab_identity-develop-admin
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildImage: true
    deployService: true
    deployEnvironment: production
    imageTags: |
      $(Build.BuildId)
      latest
    serviceName: itlab_identity
    serviceNameAdmin: itlab_identity-admin

stages:
- stage: Build
  displayName: Build images
  jobs:
  - job: BuildAdminApi
    displayName: Build Admin Api
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/itlab-identity-admin-api'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/ITLab.Identity.Admin.Api/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: ${{variables.imageTags}}
  - job: BuildAdmin
    displayName: Build Admin
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/itlab-identity-admin'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/ITLab.Identity.Admin/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: ${{variables.imageTags}}

  - job: BuildIdentity
    displayName: Build Identity
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/itlab-identity'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/ITLab.Identity.STS.Identity/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: ${{variables.imageTags}}
- stage: RestartServices
  condition: and(succeeded(), ${{variables.deployService}})
  jobs:
  - deployment: DeployAdmin
    pool:
      vmImage: 'ubuntu-latest'
    environment: ${{variables.deployEnvironment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/itlab-identity-admin:$(Build.BuildId) ${{variables.serviceNameAdmin}}'
                readyTimeout: '20000'
  - deployment: DeployIdentity
    pool:
      vmImage: 'ubuntu-latest'
    environment: ${{variables.deployEnvironment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/itlab-identity:$(Build.BuildId) ${{variables.serviceName}}'
                readyTimeout: '20000'
