version: '3.8'

services:
  identity:
    image: rtuitlab/itlab-identity
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  identity-admin:
    image: rtuitlab/itlab-identity-admin:${SERVICE_VERSION:-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - ASPNETCORE_URLS=http://*:5502
