version: '3.4'

services:
  identity:
    image: registry.rtuitlab.dev/rtuitlab/itlab-identity:${SERVICE_VERSION:-latest}
    environment:
      - ConnectionStrings__ConfigurationDbConnection=${ITLAB_IDENTITY_DB?Place identity db connection string ITLAB_IDENTITY_DB}
      - ConnectionStrings__PersistedGrantDbConnection=${ITLAB_IDENTITY_DB?Place identity db connection string ITLAB_IDENTITY_DB}
      - ConnectionStrings__IdentityDbConnection=${ITLAB_USERS_AND_EVENTS_DB?Place users and events db connection string ITLAB_USERS_AND_EVENTS_DB}
      - AdminConfiguration__IdentityAdminBaseUrl=${ITLAB_IDENTITY_ADMIN_URL?Place identity admin url ITLAB_IDENTITY_ADMIN_URL}
      - RegisterConfiguration__Enabled=false
      - USE_LOGGER_EMAIL_SENDER=false
      - EmailSenderOptions__BaseAddress=${ITLAB_EMAIL_SENDER_BASE_ADDRESS?Place email sender base address ITLAB_EMAIL_SENDER_BASE_ADDRESS}
      - EmailSenderOptions__Key=${ITLAB_EMAIL_SENDER_ACCESS_KEY?Place email sender api key ITLAB_EMAIL_SENDER_ACCESS_KEY}
      - PublicOrigin=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
  identity-admin:
    image: registry.rtuitlab.dev/rtuitlab/itlab-identity-admin:${SERVICE_VERSION:-latest}
    environment:
      - ConnectionStrings__ConfigurationDbConnection=${ITLAB_IDENTITY_DB?Place identity db connection string ITLAB_IDENTITY_DB}
      - ConnectionStrings__PersistedGrantDbConnection=${ITLAB_IDENTITY_DB?Place identity db connection string ITLAB_IDENTITY_DB}
      - ConnectionStrings__IdentityDbConnection=${ITLAB_USERS_AND_EVENTS_DB?Place users and events db connection string ITLAB_USERS_AND_EVENTS_DB}
      - ConnectionStrings__AdminLogDbConnection=${ITLAB_IDENTITY_DB?Place identity db connection string ITLAB_IDENTITY_DB}
      - ConnectionStrings__AdminAuditLogDbConnection=${ITLAB_IDENTITY_DB?Place identity db connection string ITLAB_IDENTITY_DB}
      - AdminConfiguration__ClientSecret=${ITLAB_IDENTITY_ADMIN_CLIENT_SECRET?Place identity admin auth client secret ITLAB_IDENTITY_ADMIN_CLIENT_SECRET}
      - AdminConfiguration__IdentityAdminRedirectUri=${ITLAB_IDENTITY_ADMIN_URL?Place identity admin url ITLAB_IDENTITY_ADMIN_URL}/signin-oidc
      - AdminConfiguration__IdentityServerBaseUrl=${ITLAB_IDENTITY_ISSUER?Place identity issuer ITLAB_IDENTITY_ISSUER}
      - IdentityServerData__Clients__AdminUI__ClientUri=${ITLAB_IDENTITY_ADMIN_URL?Place identity admin url ITLAB_IDENTITY_ADMIN_URL}
      - IdentityServerData__Clients__AdminUI__ClientSecrets__0__Value=${ITLAB_IDENTITY_ADMIN_CLIENT_SECRET?Place identity admin auth client secret ITLAB_IDENTITY_ADMIN_CLIENT_SECRET}
      - IdentityServerData__Clients__AdminUI__RedirectUris__0=${ITLAB_IDENTITY_ADMIN_URL?Place identity admin url ITLAB_IDENTITY_ADMIN_URL}/signin-oidc
      - IdentityServerData__Clients__AdminUI__FrontChannelLogoutUri=${ITLAB_IDENTITY_ADMIN_URL?Place identity admin url ITLAB_IDENTITY_ADMIN_URL}/signout-oidc
      - IdentityServerData__Clients__AdminUI__PostLogoutRedirectUris__0=${ITLAB_IDENTITY_ADMIN_URL?Place identity admin url ITLAB_IDENTITY_ADMIN_URL}/signout-callback-oidc
      - IdentityServerData__Clients__AdminUI__AllowedCorsOrigins__0=${ITLAB_IDENTITY_ADMIN_URL?Place identity admin url ITLAB_IDENTITY_ADMIN_URL}
      - IdentityServerData__Clients__itlab_salary__ClientSecrets__0__Value=${ITLAB_SALARY_CLIENT_SECRET?Place salary client secret ITLAB_SALARY_CLIENT_SECRET}
      - IdentityServerData__Clients__itlab_spa__RedirectUris__0=${ITLAB_IDENTITY_SPA_LOGIN_REDIRECT?Place spa redirect uri ITLAB_IDENTITY_SPA_LOGIN_REDIRECT}
      - IdentityServerData__Clients__itlab_spa__RedirectUris__1=${ITLAB_IDENTITY_SPA_SILENT_LOGIN_REDIRECT?Place spa silent redirect uri ITLAB_IDENTITY_SPA_SILENT_LOGIN_REDIRECT}
      - IdentityServerData__Clients__itlab_spa__PostLogoutRedirectUris__0=${ITLAB_IDENTITY_SPA_LOGOUT_REDIRECT?Place spa silent logout redirect uri ITLAB_IDENTITY_SPA_LOGOUT_REDIRECT}
      - IdentityServerData__Clients__itlab_spa__AllowedCorsOrigins__0=${ITLAB_IDENTITY_SPA_ALLOWED_ORIGIN?Place spa allowed origin ITLAB_IDENTITY_SPA_ALLOWED_ORIGIN}
